# Generated by Django 5.2.11 on 2026-03-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_watchhistory_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('detail_view', 'Detail View'), ('watch_click', 'Watch Click'), ('download_click', 'Download Click'), ('signup_completed', 'Signup Completed'), ('login', 'Login')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='movie.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='movie_event_event_t_3d2f76_idx'), models.Index(fields=['session_key', 'created_at'], name='movie_event_session_e9cead_idx')],
            },
        ),
    ]
