# Generated by Django 5.2.11 on 2026-03-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='movie_event_event_t_3d2f76_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='movie_event_session_e9cead_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='meta',
        ),
        migrations.AddField(
            model_name='event',
            name='link_type',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('search', 'Search'), ('detail_view', 'Detail View'), ('watch_click', 'Watch Click')], max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at', 'event_type'], name='movie_event_created_e8a8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at', 'session_key'], name='movie_event_created_ecff06_idx'),
        ),
    ]
