# Generated by Django 5.2.11 on 2026-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('search', 'Search'), ('detail_view', 'Detail View'), ('watch_click', 'Watch Click'), ('signup_completed', 'Signup Completed'), ('login', 'Login')], max_length=32),
        ),
    ]
