# Generated by Django 5.2.11 on 2026-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_moviecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True)),
                ('views_total', models.PositiveIntegerField(default=0)),
                ('watches', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('events_search', models.PositiveIntegerField(default=0)),
                ('events_detail_view', models.PositiveIntegerField(default=0)),
                ('events_watch_click', models.PositiveIntegerField(default=0)),
                ('events_signup_completed', models.PositiveIntegerField(default=0)),
                ('sessions_search', models.PositiveIntegerField(default=0)),
                ('sessions_detail', models.PositiveIntegerField(default=0)),
                ('sessions_watch', models.PositiveIntegerField(default=0)),
                ('sessions_signup', models.PositiveIntegerField(default=0)),
                ('ratings_count_total', models.PositiveIntegerField(default=0)),
                ('avg_rating_global', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
    ]
