# Generated by Django 5.2 on 2026-03-07 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_dailymetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='ETLRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, default='build_daily_metrics', max_length=120)),
                ('range_start', models.DateField()),
                ('range_end', models.DateField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='SUCCESS', max_length=20)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_name', 'started_at'], name='movie_etlru_job_nam_026d6a_idx'), models.Index(fields=['status', 'started_at'], name='movie_etlru_status_34aad0_idx')],
            },
        ),
    ]
